### ISSUE TITLE
SNMP GET: noSuchObject/noSuchInstance returned as empty value instead of unsupported (regression since 6.0.0)

### ISSUE THREAD

**Issue by alkk** [netxms/netxms#3690]
9a5a7bb457 (first shipped in 6.0.0) replaced `SnmpGetEx(..., SG_PSTRING_RESULT)` in `Node::getMetricFromSNMP()` with a hand-built PDU so the value goes through `FormatSNMPValue()` and gets display hints. The new code checks only the PDU error status (`src/server/core/node.cpp:8850` on master, `:8361` on stable-6.2), and loses two things `SnmpGetEx` did (`src/snmp/libnxsnmp/util.cpp:150-153`, `:242-247`):

1. **Exception varbinds are not rejected.** SNMPv2c/v3 GET on an OID the device does not implement answers `noError` with a `noSuchObject` / `noSuchInstance` varbind. `FormatSNMPValue()` ends up in `SNMP_Variable::getValueAsString()`, whose `default:` writes `""` (`src/snmp/libnxsnmp/variable.cpp:562`), and the function returns `DCE_SUCCESS`. Before 6.0 this was `SNMP_ERR_NO_OBJECT` → `DCE_NOT_SUPPORTED`.
2. **PDU error mapping changed.** Every non-zero error status now becomes `SNMP_ERR_NO_OBJECT` → `DCE_NOT_SUPPORTED`. Before, only `noSuchName` did; `genErr`, `tooBig` etc. were `SNMP_ERR_AGENT` → `DCE_COLLECTION_ERROR`. This one affects v1 too.

Effect of (1): a single-value SNMP DCI on an unimplemented OID stays active with an empty last value instead of going unsupported. The empty string parses as 0 in `ItemValue` (`src/server/core/dcivalue.cpp`), so numeric thresholds like `< 1` or `== 0` activate, with an empty current value in the event. `dc.snmp` level 7 logs `getMetricFromSNMP(<oid>): success`. After upgrade from 5.x, every quietly unsupported SNMP DCI on a v2c/v3 node turns into an active empty-valued one.

Affected:
- server-side single-value SNMP DCIs without raw value type (`datacoll.cpp:88`), including polling through an agent SNMP proxy — the agent passes the response PDU through unchanged
- client "get value" (`Node::getMetricForClient()`)
- status poll sysUpTime fallback (`node.cpp:3965`) — missing `sysUpTime` reads as 0 and resets boot time
- NXSL `SNMPGetValue()` (`src/server/core/nxslext.cpp:1709`), changed in the same commit: returns `""` instead of `null` for a missing OID, so scripts testing for `null` break

Not affected: DCIs with a raw value type, agent-side SNMP collection (`src/agent/core/dcsnmp.cpp:164`), table DCIs (`SetTableCellFromSNMPVariable()` skips exceptions), `SNMPTransport.getValue()`.

Fix: in both places check the varbind type before formatting — `ASN_NO_SUCH_OBJECT`, `ASN_NO_SUCH_INSTANCE`, `ASN_END_OF_MIBVIEW` → `SNMP_ERR_NO_OBJECT` — and restore `noSuchName` → `SNMP_ERR_NO_OBJECT`, anything else → `SNMP_ERR_AGENT`. Rejecting `ASN_NULL` too would be reasonable, but it is new behaviour: 5.x returned it as an empty string as well.

Same empty-value-on-exception pattern, but not a regression (already in 5.2): `SNMPTransport.getValues()`, SNMP table object tools, and the AI `snmp` tool (checks `ASN_NULL` only).

No fix on any branch as of master 835d1dc466 / stable-6.2 d7d0624671. Found by code reading, reported by a customer on 6.2.5; not reproduced here.
